### ISSUE TITLE
Propuesta de plática: Metaprogramación - Clonando Bash en Ruby en 15 minutos

### ISSUE THREAD

**Issue by aleandros** [chilangodev/platicas#1]
La idea es dar una introducción a la metaprogramación en Ruby, usando como ejemplo un pequeño DSL que haga más sencillo crear aplicaciones de linea de comandos. El reto, y lo divertido, es que sea live coding. La idea es hacerlo en 15 minutos, y si los organizadores y la gente están de acuerdo, dar 5-10 minutos extra para hablar sobre aspectos importantes de metaprogramación en Ruby (por ejemplo, cuando usarla, cuando evitarla, y quizás explorar ejemplos de proyectos exitosos)

La metaprogramación es un tema muy importante para cualquier desarrollador de ruby, siendo estos algunos de los motivos principales:
- Es fundamental para entender el modelo de objetos de Ruby, así como la manera en que se hace dispatching de un método.
- Ayuda a entender los cómos y por qués de librerías que parecen mágicas como sinatra, activerecord, rspec o thor, lo cual nos ayuda a entender errores o utilizarlas de maneras más sofisticadas.
- Es una herramienta que, bien utilizada, puede brindarnos enorme flexibilidad y productividad en nuestro código.

**Comment by vic** [comment]
:+1: suena divertido :)

**Comment by araujophillips** [comment]
Im in!

**Comment by ingscjoshua** [comment]
cuando para iR!!! :D

**Comment by captain-http** [comment]
+1

**Comment by aleandros** [comment]
¡Hola gente! Para que el demo no quede muy pobre y con poca explicación, me gustaría usar más del tiempo estándar, y extenderla a 20 minutos. Esto es si ustedes están de acuerdo. ¿Cómo ven?

**Comment by dabit** [comment]
@aleandros Gracias, nos vemos el Jueves

**Comment by dabit** [comment]
Gracias!
