### ISSUE TITLE
Deuda técnica.

### ISSUE THREAD

**Issue by mishelashala** [chilangodev/platicas#11]
Sería bastante bueno que dejáramos de lado el código por una noche y habláramos un poco más sobre desarrollo.

**Comment by dabit** [comment]
:+1:

**Comment by grillermo** [comment]
o/ Yo la doy en el próximo chilango

**Comment by dabit** [comment]
@grillermo 26 de Mayo, apuntado. Gracias!

**Comment by juankiz** [comment]
👏
