### ISSUE TITLE
Propuesta de plática: CodersLink

### ISSUE THREAD

**Issue by rafsmx** [chilangodev/platicas#12]

**Comment by rafsmx** [comment]
Hola, soy Rafael Cázares, el Director Nacional de Operaciones de CodersLink. Quisiera encontrarme con ustedes para platicarles de nuestra plataforma, cómo funcionamos y abordar sus preguntas.

www.coderslink.com

**Comment by dabit** [comment]
Hola Rafael,   

Por respeto a los patrocinadores que nos apoyan a cambio de esto no te puedo dar espacio para hablar a los asistentes, o promocionar tu servicio. Sin embargo, nada te impide asistir y hacer networking por tu cuenta con los asistentes al evento. Te mandé mas detalles por meetup.com.

Saludos!
