### ISSUE TITLE
ActiveModel

### ISSUE THREAD

**Issue by jaimerodas** [chilangodev/platicas#17]
No sé si alguien ya ha dado pláticas de ActiveModel, pero me gustaría escuchar una que tratara:
- Por qué usar ActiveModel?
- Casos de uso (Reportes, Búsquedas Avanzadas, etc.) 
- Peligros de ActiveModel (p/e usar fechas)

**Comment by captain-http** [comment]
Les podría platicar sobre mis chocoaventuras con ActiveModel si es de
interés de la comunidad.

**Comment by danpliego** [comment]
@babasbot estaría de lujo, te apuntas para el chilango de este mes?

**Comment by captain-http** [comment]
ya estan

**Comment by juankiz** [comment]
Gracias por la plática @babasbot :D

**Comment by captain-http** [comment]
De nada, si los slides le sirven a alguien están aquí: https://speakerdeck.com/babasbot/the-active-model
