### ISSUE TITLE
UI != UX

### ISSUE THREAD

**Issue by holasoymalva** [chilangodev/platicas#18]
In my time in the area of development me I liked the area of design specifically the front end but nevertheless me and found that although we work shoulder to shoulder designers with developers there is still misinformation in the area of UI and UX to the point of believing that a Ux is the one who brings color to the page or app.

I put some resources available for support :
https//:www.uxbooth.com
https//:www.uxmatters.com
https//:uxmag.com
https//:twitter.com/uxpin
https//:twitter.com/uxlinks
https//:twitter.com/ux
https//:twitter.com/UsabilityTools
https//:twitter.com/ideo
https//:twitter.com/shoobe01
https//:twitter.com/lauraklein
https//:twitter.com/jmspool
https//:www.uie.com

**Comment by danpliego** [comment]
@DeipMartin quieres dar la platica o buscamos a alguien? jaja, yo creo que podemos poner esta imagen y listo http://uxr.ie/wp-content/uploads/2015/03/ui-and-ux.png

**Comment by holasoymalva** [comment]
si amigo por mi no hay problema , cuenta conmigo

2016-09-13 11:20 GMT-05:00 danpliego notifications@github.com:
