### ISSUE TITLE
Propuesta de platica: Patrones de dieseño en Ruby (y cuales estan usados en Rails)

### ISSUE THREAD

**Issue by indie-rok** [chilangodev/platicas#2]
Siempre leo como Singleton/Factory y demás..

Nunca me he tomado el tiempo de investigarlo a fondo.

Estaría padre que alguién con experiencia en implementación pueda hablarnos de los patrones, y cuando es mejor implementarlos (y por que)

**Comment by captain-http** [comment]
+1

**Comment by aleandros** [comment]
Estaría excelente. Patrones de diseño es un tema subvaluado en muchos círculos, es útil y es conocimiento independiente de la plataforma/lenguaje

**Comment by vic** [comment]
yo quiero aprender a hacer singleton factory facade en ruby, ya!

**Comment by juankiz** [comment]
+1

**Comment by juandazapata** [comment]
Creo que "Patrones en Ruby" es un tema **demasiado amplio**. Sería una charla muy superficial, no más allá de los conceptos. Propongo que saquemos una lista de los patrones y busquemos ponentes para cada uno de ellos. El libro de Sandi Metz tiene ~15 patterns.

**Comment by juandazapata** [comment]
BTW, me apunto para exponer `factory`, `decorator`, `observer` o `adapter`. Me avisan con tiempo para preparar la charla.

**Comment by dabit** [comment]
@juandazapata te apuntas para alguna en el evento de este 21 de Abril?

**Comment by juandazapata** [comment]
@dabit seguro, doy una plática rápida acerca del **Adapter Pattern**, te parece?

**Comment by dabit** [comment]
@juandazapata anotado, gracias!
