### ISSUE TITLE
Sistemas de alto performance basados en un modelo SaaS

### ISSUE THREAD

**Issue by jyr** [chilangodev/platicas#20]
**DESCRIPCIÓN:**

Cómo construir un equipo tecnológico altamente escalable y exitoso para construir soluciones tecnológicas escalables. Escalar no solo se trata de un buen diseño y arquitectura para una plataforma SaaS, se trata sobre la arquitectura de la empresa enfocada a dar valor al negocio y no permitir puntos de fallo cuando el negocio necesita crecer. Esto inicia del eslabón más importante, que es el colaborador en la empresa, es quien debe de tener en mente para poder edificar la estructura.  

**PONENTES:**

Aldo Rivadeneira 
Jyr Gaxiola

**Comment by juankiz** [comment]
Hola @jyr la plática va a ser entre 2? Creo que nunca habíamos tenido una así, nice!

**Comment by danpliego** [comment]
@jyr me puedes compartir una foto tuya y una de Aldo para nuestro sitio y redes sociales.
