### ISSUE TITLE
Serverless en tu idioma

### ISSUE THREAD

**Issue by chillicoder** [chilangodev/platicas#23]
Platicar sobre el tema, mostrar que coincide y que es diferente de las arquitecturas existentes. Explicar que *no* es serverless.
Siete minutos es poco, tal vez en diez quedaría un poco mejor.

**Comment by danpliego** [comment]
Hola @chillicoder, disculpa los meses que tardamos en responder 😅, estamos armando la edición de este mes y queríamos saber si te interesa dar la platica de Serverless en tu idioma. El evento es el próximo Jueves 26 en Impact Hub,

Espero tu respuesta!

**Comment by chillicoder** [comment]
Claro que si, yo encantado.

**Comment by danpliego** [comment]
¡Muchas gracias! Entonces queda confirmada tu participación en el Chilango Dev de Enero.

Para la platica sería llegar a las 7:30pm el próximo jueves, puedes traer tu lap o tu presentación en una usb, contamos con adaptadores para Mac y HDMI.
Recuerda que las platicas duran máximo 10 minutos para que planees tus slides en base a eso. Y si tienes otra duda no dudes en preguntarme.

**Comment by chillicoder** [comment]
¿tienen alguna plantilla para las presentaciones?
