### ISSUE TITLE
Construyendo un banco con Elixir

### ISSUE THREAD

**Issue by jordi-adame** [chilangodev/platicas#27]
Mostraremos el porque decidimos crear un nuevo core bancario

- Por qué decidimos hacerlo en Elixir?
- Por qué decidimos usar PostgreSQL?
- Qué beneficios tiene para nosotros?
- Qué beneficios tiene para el ecosistema Fintech en México?
- Mostraremos el esquema general que estamos utilizando

Duración: 15 minutos

**Comment by danpliego** [comment]
@jordi-adame Suena muy bien, estás disponible para dar la platica el día 30 de marzo?

**Comment by jordi-adame** [comment]
@danpliego sí

**Comment by danpliego** [comment]
@jordi-adame Muchas gracias, queda confirmada tu platica para esta edición!
