### ISSUE TITLE
Factories over Constructors (JavaScript)

### ISSUE THREAD

**Issue by mishelashala** [chilangodev/platicas#3]
# Funciones de construcción en lugar de Constructores

JavaScript no es un lenguaje OO basado en clases. Punto. Se acabo. Te jodes.
P.D.: Las clases en JavaScript no tienen sentido  
### Funciones como clases

``` javascript
function Animal (nombre) {
  this.nombre = nombre;

  this.saludar = function () {
    console.log(this.nombre);
  }
}
const perro = new Animal('perro');
perro.saludar(); // "perro"
```

`this` no hace referencia a la instancia de 'Animal' creada y almacenada.
En su lugar hace referencia al contexto de ejecución; en éste caso `perro`.
¿El problema?
El contexto se puede cambiar de manera manual (y suele cambiar todo el tiempo).
¿Y si nosotros intentamos cambiarlo?

``` javascript
function Animal (nombre) {
  this.nombre = nombre;
  this.saludar = function () {
    console.log(this.name);
  }
}
var perro = new Animal('perro');
perro.saludar.bind({ nombre: 'gato' })(); // "gato"
```

Podemos "cambiar" el contexto en el que se ejecuta la propiedad saludar en este caso un objeto literal con la propiedad nombre igual a 'gato'.
¿Quien cambiaría el contexto manualmente? No tiene sentido...
Bueno, es un anti-patrón de diseño bastante utilizado en JavaScript. Gracias DOO. 
### ¿Cómo funciona `this`?

Cuando nosotros invocamos al identificador `new` precediendo la ejecución de una función
1. Se crea un nuevo contexto de ejecución (se crea un objeto llamado `this`) y se alamacena en la pila de ejecución.
2. Si dentro del cuerpo de la función hay asignaciones de propiedades a `this` estas se realizan como a cualquier otro objeto.
3. Si no se devuelve manualmente algún valor la función regresará automaticamente `this`.

¿El problema? Este anti-patrón de diseño ésta roto.

``` javascript
function Animal (nombre) {
  this.nombre = nombre;
  this.saludar = function () {
    console.log(this.nombre);
  }

  return { name: 'Chuck Testa', saludar: function () { console.log(this.name) } };
}

var perro = new Animal('perro');
// perro is that you?
perro.saludar(); // Nope, Its "Chuck Testa"
```

¿Quien haría una cosa así? Conozco gente.
### ¿Solución?

Clausuras más funciones de fabricación.

``` javascript
function crearAnimal (propiedad) {
   var nombre = propiedad.nombre || '';

  function saludar () {
    console.log(nombre);
  }

  return { saludar: saludar };
}

const perro = crearAnimal({ nombre: 'perro' });
perro.saludar(); // "perro"
```

Las funciones de fabricación (factories functions) son funciones que crean instancias de objetos, luego las inicializan y devuelven.

Las clausuras son funciones que recuerdan el ámbito en el fueron llamadas y tienen acceso a todas las variables declaradas en ese mismo ámbito.

En este caso declaramos una función dentro de otra función y la exponemos regresandola como propiedad de un objeto.
## Conclusión

NO tengo una. Solo usen funciones de fabricación y ya. A la verga.
## Referencias
1. [Clausuras - Wikipedia](https://es.wikipedia.org/wiki/Clausura_%28inform%C3%A1tica%29)
2. [Clausuras - Mozilla](https://developer.mozilla.org/es/docs/Web/JavaScript/Closures)
## Recursos
1. [The two pillars of JavaScript](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3#.y6ik3ltta)
2. [How to Fix the ES6 `class` keyword](https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf#.2du6zl4zm)
3. [Master the JavaScript Interview: What is a Closure?](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36#.qfh563b12)
4. [10 Interview Questions Every JavaScript Developer Should Know](https://medium.com/javascript-scene/10-interview-questions-every-javascript-developer-should-know-6fa6bdf5ad95#.7znhz7fzg)
5. [Common Misconceptions About Inheritance in JavaScript](https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a#.e6uvhrevk)
6. [Composition over Inheritance](https://medium.com/humans-create-software/composition-over-inheritance-cb6f88070205#.u9bn4xpxb)
7. [Constructors Are Bad For JavaScript](https://medium.com/humans-create-software/factory-functions-in-javascript-video-d38e49802555#.f3i1rbqbb)
8. [Javascript OO Without Constructors](http://tobyho.com/2012/10/21/javascript-OO-without-constructors/)
9. [JS Objects: Inherited a Mess](https://davidwalsh.name/javascript-objects)
10. [JS Objects: De”construct”ion](https://davidwalsh.name/javascript-objects-deconstruction)
11. [Myth: JavaScript needs classes](http://www.2ality.com/2011/11/javascript-classes.html)
12. [Prototypal Inheritance in JavaScript](http://javascript.crockford.com/prototypal.html)

**Comment by mishelashala** [comment]
@dabit ¿7 minutos?

**Comment by dabit** [comment]
Es el tiempo estándar de las pláticas en nuestros eventos, pero si necesitas más tiempo puedo poner el tag de 15 minutos.

Creo que me falta poner en el README que lo especifiquen.

**Comment by mishelashala** [comment]
@dabit ¡JAJAJA! Las platicas siempre se prolongan. No importa, con 7 minutos me basta.

**Comment by dabit** [comment]
@MichelAyala gracias, nos vemos el Jueves

**Comment by dabit** [comment]
@MichelAyala Muchísimas gracias!
