### ISSUE TITLE
¿Como armar una imagen de Docker from scratch para Rails?

### ISSUE THREAD

**Issue by captain-http** [chilangodev/platicas#4]
Hace un par de semanas tuve que armar una imagen de Docker para una aplicación de rails. En dockerhub circulan un monton de imagenes, pero son bastante pesadas > 1GB.

Podría armar en vivo una imagen de Docker basada en alpine, que pesará cerca de 300 mb con:

Ademas podemos dar algunas recomendaciónes para armar un buen Dockerfile.

**Comment by aleandros** [comment]
+1000
Las imágenes lentas de construir son un pain in the ass a la hora de hacer deployment y nunca le he dedicado tiempo a optimizar ese aspecto. Me late bastante.

**Comment by dabit** [comment]
7 minutos o 15 minutos?

**Comment by captain-http** [comment]
con 7 minutos la armo

**Comment by juankiz** [comment]
Suena cool +1

**Comment by rash-pro** [comment]
Armate el demo @babasbot  :D +1

**Comment by dabit** [comment]
@babasbot Nos vemos el jueves!

**Comment by dabit** [comment]
@babasbot Gracias!
