### ISSUE TITLE
Patrones de diseño y otras cosas en Ruby

### ISSUE THREAD

**Issue by holasoymalva** [chilangodev/platicas#5]
# Patrones de diseño y otras cosas en Ruby
## ¿Patrones de diseño?

Si patrones de diseño, los patrones de diseño son soluciones para problemas típicos que nos podemos encontrar a la hora de desarrollar una aplicación y aunque nuestra aplicación sea única, tendrá partes en comun con otras aplicaciones .
## ¿Por qué usar patrones de diseño?

Si queremos desarrollar aplicaciones robustas y fáciles de mantener, debemos cumplir ciertos "estandares".Los patrones de diseño nos ayudan a cumplir muchos de estos principios o reglas de diseño. Programación SOLID, control de cohesión y acoplamiento o reutilización de código son algunos de los beneficios que podemos conseguir al utilizar patrones.
## ¿Tengo que aprender todos los patrones de diseño?

Patrones de diseño hay muchos. Muchísimos. Y siguen apareciendo patrones nuevos cada poco tiempo. El desarrollo de aplicaciones es una disciplina en constante cambio. Algo particular de los patrones es que no son explusivos de las ciencias computacionales ya que existen en la naturaleza " Biomorfismo " y son aplicados en multiples areas del conocimiento.
## ¿Cuales son los tipos de patrones existen?

Patrones creacionales
Patrones de comportamiento
Patrones estructurales

Algunos ejemplos de patrones en ruby:
(ejemplos de codigo)
-Singleton
-Strategy Lambdas
-Strategy
-Iterator: malas practicas vs buenas practicas
-Observer
-Adapter

Uso  en rails & Hanami(LOTUS)
## Conclusiones

Entender sus consecuencias, y su porqué, sí sirve.
Memorizar los patrones y usarlos a cada oportunidad no ayuda. 
Entiende el contexto.
# Referencias

[Patrón de diseño- Wikipedia](https://es.wikipedia.org/wiki/Patr%C3%B3n_de_dise%C3%B1o)
[Design patterns and assets- Mozilla](https://developer.mozilla.org/en-US/Apps/Design/Design_patterns_and_assets)
# Recursos

https://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/39-ruby-s-object-model/lessons/131-singleton-methods-and-metaclasses
https://practicingruby.com/articles/ruby-and-the-singleton-pattern-dont-get-along
http://ruby-doc.org/stdlib-1.9.3/libdoc/singleton/rdoc/Singleton.html
http://dalibornasevic.com/posts/9-ruby-singleton-pattern
http://www.devalot.com/articles/2008/09/ruby-singleton
http://www.genbetadev.com/metodologias-de-programacion/doce-principios-de-diseno-que-todo-desarrollador-deberia-conocer
https://blog.8thlight.com/josh-cheek/2012/10/20/implementing-and-testing-the-singleton-pattern-in-ruby.html
http://ruby-doc.org/stdlib-2.0.0/libdoc/observer/rdoc/Observable.html
http://www.sitepoint.com/design-patterns-in-ruby-observer-singletn/
http://api.rubyonrails.org/v3.2.0/classes/ActiveRecord/Observer.html
http://docs.ruby-lang.org/en/2.2.0/Observable.html
https://dockyard.com/blog/2013/07/25/design-patterns-strategy-pattern
http://edapx.com/2013/11/27/strategy-pattern/
http://stackoverflow.com/questions/3570611/cheat-sheet-for-all-design-patterns-implemented-in-ruby
http://stackoverflow.com/questions/12508414/about-strategy-pattern-and-rails
https://github.com/nslocum/design-patterns-in-ruby
http://hanamirb.org/

**Comment by captain-http** [comment]
+1

**Comment by danpliego** [comment]
@DeipMartin Muchas gracias por la platica!
